"""Integration helpers for generated-model AC-dipole reconstruction.

The AC-dipole layer builds on :func:`tmom_recon.model.resolve_model_details` with
two generated models: an undriven transport model that keeps the marker in place,
and a driven optics model with the AC dipole installed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from tmom_recon.model import ModelDetails, resolve_model_details
from tmom_recon.physics.closed_orbit import parse_plane_spec

from .madng_driver import ACDipoleMadDriver
from .reconstruction import SUMMARY_ATTR_NAME

if TYPE_CHECKING:
    import pandas as pd


__all__ = [
    "ACDipoleConfig",
    "ResolvedACDipoleConfig",
    "apply_precomputed_ac_dipole_bpm_overrides",
    "resolve_ac_dipole_config",
]


@dataclass(frozen=True)
class ACDipoleConfig:
    """Driven AC-dipole settings layered on generated model details."""

    ac_dipole_marker: str
    driven_tunes: tuple[float, float]
    bpm_upstream: str | None = None
    bpm_downstream: str | None = None
    smooth_lambda: float = 1.0
    barrier_s: float | None = None
    data_mean_closed_orbit_planes: str | None = None
    """Planes in which to take the closed orbit from the measured data rather
    than from the model twiss.

    ``None`` (the default) or ``""`` takes the closed orbit directly from the
    ``dp/p=0`` model twiss in both planes. Pass ``"x"``, ``"y"``, ``"xy"`` or
    ``"yx"`` (case-insensitive, any order) to instead use the per-BPM turn-mean
    of the data in those planes — valid because an AC-dipole driven oscillation
    has ~zero mean over the flat-top turns. That orbit is removed before the
    betatron reconstruction and restored afterwards, its angle inferred from its
    own positions with the model optics. Use this when the model twiss does not
    represent the machine closed orbit in that plane."""

    def __post_init__(self) -> None:
        # Fail on a bad plane spec at construction, not deep inside a MAD-NG run.
        parse_plane_spec(self.data_mean_closed_orbit_planes, field="data_mean_closed_orbit_planes")


@dataclass(frozen=True)
class ResolvedACDipoleConfig:
    """Generated ACD model inputs with explicitly separate twisses and models.

    Two models are needed: ``install_ac_dipole`` *replaces and removes* the
    AC-dipole element, which is the transport anchor, so the driven optics cannot
    come from the transport model.

    Attributes:
        config: The :class:`ACDipoleConfig` this was resolved from.
        model: Undriven MAD-NG driver used for state transport (AC-dipole element
            intact).
        optics_model: Separate driven MAD-NG driver, used only for the optics
            twiss (regenerated by the generator when magnets change).
        optics_tws: Driven, off-momentum optics twiss.
        tracking_tws: Undriven, off-momentum twiss used for finite dispersion.
        closed_orbit_tws: Undriven, ``dp/p=0`` closed-orbit reference twiss.
    """

    config: ACDipoleConfig
    model: ACDipoleMadDriver
    optics_model: ACDipoleMadDriver
    optics_tws: pd.DataFrame
    tracking_tws: pd.DataFrame
    closed_orbit_tws: pd.DataFrame


def resolve_ac_dipole_config(
    model_details: ModelDetails, config: ACDipoleConfig
) -> ResolvedACDipoleConfig:
    """Generate the undriven transport model and a separate driven optics model.

    The undriven ``dp/p=0`` closed orbit is taken from the transport model; the
    driven optics come from a second model with the AC dipole installed.
    """
    tracking_model = ACDipoleMadDriver(
        accelerator=model_details.accelerator,
        pt=model_details.pt,
        observed_elements=config.ac_dipole_marker,
        magnet_strengths=model_details.magnet_strengths,
        install_ac_dipole_markers=True,
        tune_knobs_file=model_details.tune_knobs_file,
        corrector_knobs_file=model_details.corrector_knobs_file,
    )
    tracking_model.twiss_elements = tracking_model.run_twiss(observe=0)
    closed_orbit_tws = tracking_model.run_twiss(observe=1, coupling=True, deltap=0.0)
    tracking_tws = tracking_model.run_twiss(observe=1, coupling=True, pt=tracking_model.pt)

    optics = resolve_model_details(
        model_details,
        observed_elements=config.ac_dipole_marker,
        install_ac_dipole_markers=True,
    )
    natural = optics.model.run_twiss(observe=0, coupling=True, pt=optics.model.pt)
    # install_ac_dipole takes an explicit deltap (its own API, not a twiss
    # closed-orbit search), so the pt -> dp/p conversion is still required here.
    optics.model.install_ac_dipole(
        nat_tunes=(float(natural.headers["q1"] % 1.0), float(natural.headers["q2"] % 1.0)),
        drv_tunes=(float(config.driven_tunes[0]), float(config.driven_tunes[1])),
        deltap=optics.model.accelerator.pt2dp(optics.model.pt),
    )
    optics_tws = optics.model.run_twiss(observe=1, coupling=True, pt=optics.model.pt)
    return ResolvedACDipoleConfig(
        config=config,
        model=tracking_model,
        optics_model=optics.model,
        optics_tws=optics_tws,
        tracking_tws=tracking_tws,
        closed_orbit_tws=closed_orbit_tws,
    )


def apply_precomputed_ac_dipole_bpm_overrides(
    result: pd.DataFrame,
    acd_result: pd.DataFrame,
) -> pd.DataFrame:
    """Patch ``px``/``py`` for the BPMs adjacent to the AC dipole."""
    bpm_upstream = acd_result.attrs["bpm_upstream"]
    bpm_downstream = acd_result.attrs["bpm_downstream"]

    out = result.copy(deep=True)
    out.attrs["ac_dipole_marker"] = acd_result.attrs["acd_marker"]
    out.attrs["ac_dipole_bpm_upstream"] = bpm_upstream
    out.attrs["ac_dipole_bpm_downstream"] = bpm_downstream
    out.attrs["ac_dipole_smooth_lambda"] = float(acd_result.attrs["smooth_lambda"])

    summary = acd_result.attrs[SUMMARY_ATTR_NAME]
    for bpm_name, px_col, py_col in (
        (bpm_upstream, "px_bpm_upstream_cleaned", "py_bpm_upstream_cleaned"),
        (bpm_downstream, "px_bpm_downstream_cleaned", "py_bpm_downstream_cleaned"),
    ):
        mask = out["name"].astype(str) == bpm_name
        if not mask.any():
            continue
        side = (
            summary[["turn", px_col, py_col]]
            .rename(columns={px_col: "px", py_col: "py"})
            .set_index("turn")
        )
        turns = out.loc[mask, "turn"].to_numpy()
        out.loc[mask, "px"] = side.reindex(turns)["px"].to_numpy(dtype=float)
        out.loc[mask, "py"] = side.reindex(turns)["py"].to_numpy(dtype=float)
    return out
