"""
Common pytest fixtures for MAD interface tests.

This module contains shared fixtures used across MAD interface test modules.
"""

from __future__ import annotations

import logging
import shutil
from collections import OrderedDict
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from tests.psb_tracking import create_psb_model_dir
from tests.support.lhc import tracking_artifacts_loader
from tests.support.psb import PSBScenario
from tests.support.scenarios import scenario as build_psb_scenario

if TYPE_CHECKING:
    from collections.abc import Callable

# Configure logging for tests
logging.getLogger("xdeps").setLevel(logging.WARNING)


_AUTOGENERATED_LATTICE_SUFFIXES = {".json", ".mad"}
_PSB_TRACKING_SCENARIO_CACHE_SIZE = 4


@pytest.fixture(scope="session")
def data_dir() -> Path:
    """Path to the test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture(scope="session", autouse=True)
def cleanup_autogenerated_lattice_files(data_dir: Path):
    """Remove MAD-NG/xsuite cache files generated during the test session."""
    sequences_dir = data_dir / "sequences"
    existing_files = {
        path.resolve()
        for suffix in _AUTOGENERATED_LATTICE_SUFFIXES
        for path in sequences_dir.glob(f"*{suffix}")
    }

    yield

    for suffix in _AUTOGENERATED_LATTICE_SUFFIXES:
        for path in sequences_dir.glob(f"*{suffix}"):
            if path.resolve() not in existing_files:
                path.unlink(missing_ok=True)


@pytest.fixture(scope="session")
def seq_b1(data_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Return the session-local copy of the beam-1 sequence.

    ``xtrack_tools`` stores the generated Xsuite environment next to the
    sequence. The suite deliberately runs without xdist, so one session-local cache is
    both safe and reusable across all line-dependent tests.
    """
    source = data_dir / "sequences" / "lhcb1.seq"
    worker_dir = tmp_path_factory.mktemp("lhcb1")
    destination = worker_dir / source.name
    shutil.copy2(source, destination)
    return destination


@pytest.fixture(scope="session")
def psb_model_dir(data_dir: Path) -> Path:
    """Create a temporary PSB ring-3 model and its MAD-X saved sequence."""
    return create_psb_model_dir((data_dir / "acc-models-psb").resolve())


@pytest.fixture(scope="session")
def seq_psb3(psb_model_dir: Path) -> Path:
    """Path to the generated PSB ring-3 sequence."""
    return psb_model_dir / "psb3_saved.seq"


@pytest.fixture(scope="session")
def xsuite_json_path(
    data_dir: Path, tmp_path_factory: pytest.TempPathFactory
) -> Callable[[str], Path]:
    """Get the xsuite JSON path for a given sequence file.

    Returns a callable that takes a sequence file name (e.g., "lhcb1.seq")
    and returns the path to its pre-generated JSON file in data/sequences.
    """
    # Keep generated Xsuite caches outside the checkout; one serial pytest
    # session can safely share this directory.
    sequences_dir = tmp_path_factory.mktemp("xsuite-cache")

    def _get_json_path(seq_file: str) -> Path:
        # Extract base name without extension and create JSON path
        return sequences_dir / Path(seq_file).with_suffix(".json")

    return _get_json_path


@pytest.fixture(scope="session")
def tracking_artifacts(xsuite_json_path):
    """Return the session-owned LHC tracking-scenario loader.

    The loader caches each distinct tracking condition and returns defensive
    copies, so coordinate-specific tests do not retrack or share mutable data.
    """
    return tracking_artifacts_loader(xsuite_json_path)


@pytest.fixture(scope="session")
def tracking_setup(tracking_artifacts):
    """Compatibility wrapper returning tracking data, twiss, and truth."""

    def _get(
        seq_file: Path,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
    ):
        artifacts = tracking_artifacts(
            seq_file,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
        )
        return artifacts.data

    return _get


@pytest.fixture(scope="session")
def psb_tracking_setup(psb_model_dir: Path):
    """Return lazily generated PSB scenarios for the entire pytest session.

    Returns a factory ``_get(delta_p)`` yielding a fresh
    :class:`tests.support.psb.PSBScenario` built by
    :func:`tests.psb_tracking.build_psb_tracking_setup`.

    Each requested momentum condition is tracked once, then every consumer gets
    a copy of its mutable tables.  Expensive model objects remain session-owned.
    """

    _cache: OrderedDict[float, PSBScenario] = OrderedDict()

    def _load(delta_p: float):
        if delta_p not in _cache:
            _cache[delta_p] = build_psb_scenario(psb_model_dir, delta_p=delta_p)
            if len(_cache) > _PSB_TRACKING_SCENARIO_CACHE_SIZE:
                _cache.popitem(last=False)
        else:
            _cache.move_to_end(delta_p)
        return _cache[delta_p]

    def _get(delta_p: float = 0.0):
        return _load(float(delta_p)).copy()

    return _get


@pytest.fixture(scope="session")
def psb_scenarios(psb_model_dir: Path):
    """Return a session-cached factory for explicit PSB error scenarios.

    The cache key is the complete keyword scenario specification.  It keeps
    error-family tests independent while avoiding duplicate tracking when they
    assert different coordinates or reconstruction properties of one scenario.
    """
    cache: OrderedDict[tuple[tuple[str, object], ...], PSBScenario] = OrderedDict()

    def get(**kwargs) -> PSBScenario:
        key = tuple(sorted(kwargs.items()))
        if key not in cache:
            cache[key] = build_psb_scenario(psb_model_dir, **kwargs)
            if len(cache) > _PSB_TRACKING_SCENARIO_CACHE_SIZE:
                cache.popitem(last=False)
        else:
            cache.move_to_end(key)
        return cache[key].copy()

    return get


@pytest.fixture(scope="session")
def acd_tracking_setup(tracking_artifacts):
    """Expose session-owned LHC scenarios through the historical fixture API."""

    def _get(
        seq_file: Path,
        *,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
        state_markers: bool = False,
        include_line: bool = False,
    ):
        return tracking_artifacts(
            seq_file,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
            state_markers=state_markers,
            include_line=include_line,
        )

    return _get
