"""
Common pytest fixtures for MAD interface tests.

This module contains shared fixtures used across MAD interface test modules.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from tests.psb_tracking import create_psb_model_dir
from tests.support.lhc import tracking_artifacts_loader
from tests.support.psb import PSBScenario
from tests.support.scenarios import scenario as build_psb_scenario

if TYPE_CHECKING:
    from collections.abc import Callable

# Configure logging for tests
logging.getLogger("xdeps").setLevel(logging.WARNING)


_AUTOGENERATED_LATTICE_SUFFIXES = {".json", ".mad"}


@pytest.fixture(scope="session")
def data_dir() -> Path:
    """Path to the test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture(scope="session", autouse=True)
def cleanup_autogenerated_lattice_files(data_dir: Path):
    """Remove MAD-NG/xsuite cache files generated during the test session."""
    sequences_dir = data_dir / "sequences"
    existing_files = {
        path.resolve()
        for suffix in _AUTOGENERATED_LATTICE_SUFFIXES
        for path in sequences_dir.glob(f"*{suffix}")
    }

    yield

    for suffix in _AUTOGENERATED_LATTICE_SUFFIXES:
        for path in sequences_dir.glob(f"*{suffix}"):
            if path.resolve() not in existing_files:
                path.unlink(missing_ok=True)


@pytest.fixture(scope="session")
def seq_b1(data_dir: Path, tmp_path_factory: pytest.TempPathFactory, worker_id: str) -> Path:
    """Return a worker-local copy of the beam-1 sequence.

    ``xtrack_tools`` stores the generated xsuite environment next to the
    sequence as ``lhcb1.json``.  A shared sequence path lets xdist workers
    concurrently write/read that cache, which can expose a partially-written
    JSON file.  Keeping the sequence and its cache in a worker-specific
    temporary directory makes the fixture safe with parallel pytest runs.
    """
    source = data_dir / "sequences" / "lhcb1.seq"
    worker_dir = tmp_path_factory.mktemp(f"lhcb1-{worker_id}")
    destination = worker_dir / source.name
    shutil.copy2(source, destination)
    return destination


@pytest.fixture(scope="session")
def psb_model_dir(data_dir: Path) -> Path:
    """Create a temporary PSB ring-3 model and its MAD-X saved sequence."""
    return create_psb_model_dir((data_dir / "acc-models-psb").resolve())


@pytest.fixture(scope="session")
def seq_psb3(psb_model_dir: Path) -> Path:
    """Path to the generated PSB ring-3 sequence."""
    return psb_model_dir / "psb3_saved.seq"


@pytest.fixture(scope="session")
def xsuite_json_path(
    data_dir: Path, tmp_path_factory: pytest.TempPathFactory, worker_id: str
) -> Callable[[str], Path]:
    """Get the xsuite JSON path for a given sequence file.

    Returns a callable that takes a sequence file name (e.g., "lhcb1.seq")
    and returns the path to its pre-generated JSON file in data/sequences.
    """
    # xtrack_tools writes this file directly and does not coordinate parallel
    # writers.  Keep generated caches outside the shared checkout so xdist
    # workers cannot read one another's partially-written JSON.
    sequences_dir = tmp_path_factory.mktemp(f"xsuite-cache-{worker_id}")

    def _get_json_path(seq_file: str) -> Path:
        # Extract base name without extension and create JSON path
        return sequences_dir / Path(seq_file).with_suffix(".json")

    return _get_json_path


@pytest.fixture(scope="module")
def tracking_artifacts(xsuite_json_path):
    """Return the cached LHC artifact loader."""
    return tracking_artifacts_loader(xsuite_json_path)


@pytest.fixture(scope="module")
def tracking_setup(tracking_artifacts):
    """Compatibility wrapper returning tracking data, twiss, and truth."""

    def _get(
        seq_file: str,
        data_dir: Path,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
    ):
        artifacts = tracking_artifacts(
            seq_file,
            data_dir,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
        )
        return artifacts.data, artifacts.measurement_twiss, artifacts.truth

    return _get


@pytest.fixture(scope="module")
def psb_tracking_setup(psb_model_dir: Path):
    """PSB ring-3 AC-dipole tracking setup, keyed by ``delta_p``, built once per module.

    Returns a factory ``_get(delta_p)`` yielding a fresh
    :class:`tests.support.psb.PSBScenario` built by
    :func:`tests.psb_tracking.build_psb_tracking_setup`.

    Module-scoped so only one test file's worth of PSB tracking bundles is resident
    at a time; within a module, repeated calls for the same ``delta_p`` reuse the
    same scenario instead of re-tracking.
    """

    _cache: dict[float, PSBScenario] = {}

    def _load(delta_p: float):
        if delta_p in _cache:
            return _cache[delta_p]
        bundle = build_psb_scenario(psb_model_dir, delta_p=delta_p)
        _cache[delta_p] = bundle
        return bundle

    def _get(delta_p: float = 0.0):
        return _load(float(delta_p)).copy()

    return _get


@pytest.fixture(scope="module")
def psb_scenarios(psb_model_dir: Path):
    """Return the named PSB scenario factory bound to the generated model."""
    return lambda **kwargs: build_psb_scenario(psb_model_dir, **kwargs)


@pytest.fixture(scope="module")
def acd_tracking_setup(tracking_artifacts):
    """Compatibility wrapper exposing the richer tracking artifact bundle."""

    def _get(
        seq_file: str,
        data_dir: Path,
        *,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
        state_markers: bool = False,
    ):
        return tracking_artifacts(
            seq_file,
            data_dir,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
            state_markers=state_markers,
        )

    return _get
