"""
Common pytest fixtures for MAD interface tests.

This module contains shared fixtures used across MAD interface test modules.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest
from xtrack_tools.acd import run_acd_track

from tests.momentum.momentum_test_utils import get_truth, xsuite_to_ngtws
from tests.psb_tracking import build_psb_tracking_setup

if TYPE_CHECKING:
    from collections.abc import Callable

# Configure logging for tests
logging.getLogger("xdeps").setLevel(logging.WARNING)


_AUTOGENERATED_LATTICE_SUFFIXES = {".json", ".mad"}


@dataclass(frozen=True)
class TrackingArtifacts:
    """Cached tracking outputs shared across slow integration tests."""

    tracking_df: Any
    tws: Any
    truth: Any
    tws_xsuite: Any
    baseline_line: Any
    baseline_twiss_4d: Any


@pytest.fixture(scope="session")
def data_dir() -> Path:
    """Path to the test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture(scope="session", autouse=True)
def cleanup_autogenerated_lattice_files(data_dir: Path):
    """Remove MAD-NG/xsuite cache files generated during the test session."""
    sequences_dir = data_dir / "sequences"
    existing_files = {
        path.resolve()
        for suffix in _AUTOGENERATED_LATTICE_SUFFIXES
        for path in sequences_dir.glob(f"*{suffix}")
    }

    yield

    for suffix in _AUTOGENERATED_LATTICE_SUFFIXES:
        for path in sequences_dir.glob(f"*{suffix}"):
            if path.resolve() not in existing_files:
                path.unlink(missing_ok=True)


@pytest.fixture(scope="session")
def seq_b1(data_dir: Path) -> Path:
    """Path to the example sequence file for beam 1 used by several tests."""
    return data_dir / "sequences" / "lhcb1.seq"


@pytest.fixture(scope="session")
def seq_psb3(data_dir: Path) -> Path:
    """Path to the example sequence file for PSB ring 3 used by several tests."""
    return data_dir / "sequences" / "psb3_saved.seq"


@pytest.fixture(scope="session")
def xsuite_json_path(data_dir: Path) -> Callable[[str], Path]:
    """Get the xsuite JSON path for a given sequence file.

    Returns a callable that takes a sequence file name (e.g., "lhcb1.seq")
    and returns the path to its pre-generated JSON file in data/sequences.
    """
    sequences_dir = data_dir / "sequences"

    def _get_json_path(seq_file: str) -> Path:
        # Extract base name without extension and create JSON path
        return sequences_dir / Path(seq_file).with_suffix(".json")

    return _get_json_path


def _copy_if_possible(value: Any):
    copy_method = getattr(value, "copy", None)
    if callable(copy_method):
        try:
            return copy_method(deep=True)
        except TypeError:
            return copy_method()
    return value


def _copy_tracking_artifacts(artifacts: TrackingArtifacts) -> TrackingArtifacts:
    return TrackingArtifacts(
        tracking_df=artifacts.tracking_df.copy(deep=True),
        tws=artifacts.tws.copy(deep=True),
        truth=artifacts.truth.copy(deep=True),
        tws_xsuite=_copy_if_possible(artifacts.tws_xsuite),
        baseline_line=_copy_if_possible(artifacts.baseline_line),
        baseline_twiss_4d=_copy_if_possible(artifacts.baseline_twiss_4d),
    )


_SEQUENCE_DECLARATION = re.compile(r"^\s*([A-Za-z_][\w.]*)\s*:\s*sequence\b", re.IGNORECASE)


def _sequence_name_from_file(seq: Path) -> str:
    """Return the MAD-X sequence name declared in a file, falling back to the stem."""
    with seq.open(encoding="utf-8") as handle:
        for line in handle:
            match = _SEQUENCE_DECLARATION.match(line)
            if match:
                return match.group(1)
    return seq.stem


@pytest.fixture(scope="module")
def tracking_artifacts(xsuite_json_path):
    """Return ACD tracking artifacts for a sequence, built once per test module.

    Module-scoped (rather than a session-wide cache) so at most one test file's
    worth of tracking bundles is resident at a time: each holds a full xtrack
    Line (~240 MB), and this machine does not have the memory to keep several
    modules' worth alive simultaneously. Within a module, repeated calls with
    identical arguments share the same dict entry so tests in the same file
    still only pay the tracking cost once.
    """

    _cache: dict[tuple, TrackingArtifacts] = {}

    def _load(
        seq_path: str,
        json_path: str,
        acd_marker: str,
        sequence_name: str,
        delta_p: float,
        ramp_turns: int,
        flattop_turns: int,
        state_markers: bool,
    ):
        key = (
            seq_path,
            json_path,
            acd_marker,
            sequence_name,
            delta_p,
            ramp_turns,
            flattop_turns,
            state_markers,
        )
        if key in _cache:
            return _cache[key]
        tracking_df, tws_xsuite, baseline_line = run_acd_track(
            sequence_file=Path(seq_path),
            acd_marker=acd_marker,
            sequence_name=sequence_name,
            json_path=Path(json_path),
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
            state_markers=state_markers,
        )
        tws = xsuite_to_ngtws(tws_xsuite)
        truth = get_truth(tracking_df, tws)
        artifacts = TrackingArtifacts(
            tracking_df=tracking_df,
            tws=tws,
            truth=truth,
            tws_xsuite=tws_xsuite,
            baseline_line=baseline_line,
            baseline_twiss_4d=baseline_line.twiss(method="4d"),
        )
        _cache[key] = artifacts
        return artifacts

    def _get(
        seq_file: str,
        data_dir: Path,
        acd_marker: str = "MKQA.6L4.B1",
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
        state_markers: bool = False,
    ):
        seq = data_dir / "sequences" / seq_file
        json_path = xsuite_json_path(seq_file)
        sequence_name = _sequence_name_from_file(seq)
        return _copy_tracking_artifacts(
            _load(
                str(seq),
                str(json_path),
                acd_marker,
                sequence_name,
                delta_p,
                ramp_turns,
                flattop_turns,
                state_markers,
            )
        )

    return _get


@pytest.fixture(scope="module")
def tracking_setup(tracking_artifacts):
    """Compatibility wrapper returning tracking data, twiss, and truth."""

    def _get(
        seq_file: str,
        data_dir: Path,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
    ):
        artifacts = tracking_artifacts(
            seq_file,
            data_dir,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
        )
        return artifacts.tracking_df, artifacts.tws, artifacts.truth

    return _get


@pytest.fixture(scope="module")
def psb_tracking_setup(data_dir: Path):
    """PSB ring-3 AC-dipole tracking setup, keyed by ``delta_p``, built once per module.

    Returns a factory ``_get(delta_p)`` yielding a fresh copy of the bundle built by
    :func:`tests.psb_tracking.build_psb_tracking_setup` (``tracking_df``, ``tws``,
    ``truth``, ``model`` and ``delta_p``).

    Module-scoped so only one test file's worth of PSB tracking bundles is resident
    at a time; within a module, repeated calls for the same ``delta_p`` reuse the
    same dict entry instead of re-tracking.
    """

    _cache: dict[float, dict[str, Any]] = {}

    def _load(delta_p: float):
        if delta_p in _cache:
            return _cache[delta_p]
        bundle = build_psb_tracking_setup(data_dir, delta_p)
        _cache[delta_p] = bundle
        return bundle

    def _get(delta_p: float = 0.0):
        bundle = _load(float(delta_p))
        return {
            "tracking_df": bundle["tracking_df"].copy(deep=True),
            "tws": bundle["tws"].copy(deep=True),
            "truth": bundle["truth"].copy(deep=True),
            "model": bundle["model"],
            "delta_p": bundle["delta_p"],
            "bend_k0": dict(bundle["bend_k0"]),
        }

    return _get


@pytest.fixture(scope="module")
def acd_tracking_setup(tracking_artifacts):
    """Compatibility wrapper exposing the richer tracking artifact bundle."""

    def _get(
        seq_file: str,
        data_dir: Path,
        *,
        delta_p: float = 0.0,
        ramp_turns: int = 1000,
        flattop_turns: int = 100,
        state_markers: bool = False,
    ):
        artifacts = tracking_artifacts(
            seq_file,
            data_dir,
            delta_p=delta_p,
            ramp_turns=ramp_turns,
            flattop_turns=flattop_turns,
            state_markers=state_markers,
        )
        return {
            "tracking_df": artifacts.tracking_df,
            "tws": artifacts.tws,
            "truth": artifacts.truth,
            "tws_xsuite": artifacts.tws_xsuite,
            "baseline_line": artifacts.baseline_line,
            "baseline_twiss_4d": artifacts.baseline_twiss_4d,
        }

    return _get
