"""Derive the momentum dispersion ``D'`` from measured position dispersion.

A BPM measures position, so a momentum scan yields ``Dx``/``Dy`` and nothing
else.  ``D'`` is not lost, though: dispersion propagates exactly like a
trajectory, so the pair :math:`(D, D')` at one BPM is mapped to the next by the
same transfer matrix that maps :math:`(x, p_x)`.  One measured ``D`` at each of
two BPMs therefore determines ``D'`` at the first, which is what
:func:`derive_momentum_dispersion` does.

This is the method omc3 uses in ``optics_measurements.dispersion._calculate_dp``,
reimplemented here in this package's lowercase MAD-NG column convention and
extended with error propagation, which the omc3 version does not provide.

It is not a transcription. omc3 builds :math:`m_{11}` and :math:`m_{12}` from
pandas Series indexed by BPM name, e.g.
``np.sqrt(df.loc[shifted, "BETX"] / df.loc[:, "BETX"])``. ``shifted`` is a
permutation of the same labels, so pandas aligns the two operands and that ratio
evaluates to exactly 1 -- the :math:`\beta_{i+1}/\beta_i` factor is silently
dropped, and with it every dependence on the *next* BPM's optics. The error
cancels out of the final ratio when the measurement equals the model, which is
why the two agree on a round trip, but not for a real measurement. This
implementation works on numpy arrays, where position and not label decides what
pairs with what.

The dipole term is what makes it exact rather than approximate.  Between two
BPMs the dispersion obeys an *inhomogeneous* equation -- bends generate
dispersion along the way -- so the homogeneous :math:`2\\times 2` map alone does
not connect :math:`D_i` to :math:`D_{i+1}`.  The generated part is taken from
the model as the residual its own dispersion needs beyond homogeneous
propagation,

.. math::

   m_{13} = D^{\\mathrm{mdl}}_{i+1} - m_{11} D^{\\mathrm{mdl}}_i
            - m_{12} D'^{\\mathrm{mdl}}_i,

and subtracted from the measurement.  Only this bend contribution is model
sourced; both dispersion values entering the answer are measured.  Because
:math:`m_{13}` absorbs everything between the two BPMs, the pair need not be
physically adjacent -- a measurement covering a subset of the ring's BPMs is
handled correctly, each row simply pairing with the next one present.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:  # pragma: no cover - typing helpers only
    import pandas as pd

LOGGER = logging.getLogger(__name__)

#: Smallest :math:`|\sin \Delta\phi|` accepted between a BPM and its successor.
#: ``D'`` is recovered by dividing by :math:`m_{12} \propto \sin \Delta\phi`, so a
#: pair separated by close to a half-integer phase advance carries almost no
#: information about the angle and inverts into a large, noise-dominated value.
#: Rather than return that silently, such a pair raises: the fix is a different
#: BPM set, not a quieter threshold.
MIN_SIN_PHASE_ADVANCE = 0.05

#: Per-plane model column names: (beta, alpha, phase, dispersion, momentum
#: dispersion, tune header).
_PLANE_COLUMNS = {
    "x": ("betx", "alfx", "mu1", "dx", "dpx", "q1"),
    "y": ("bety", "alfy", "mu2", "dy", "dpy", "q2"),
}


def _plane_momentum_dispersion(
    *,
    measured_d: np.ndarray,
    measured_d_err: np.ndarray,
    beta: np.ndarray,
    alfa: np.ndarray,
    mu: np.ndarray,
    model_d: np.ndarray,
    model_dp: np.ndarray,
    tune: float,
    names: np.ndarray,
    plane: str,
) -> tuple[np.ndarray, np.ndarray]:
    """Solve ``D'`` and its uncertainty for one plane. See the module docstring."""
    nxt = np.roll(np.arange(len(beta)), -1)

    # Phase advance to the next BPM, in turns. The final entry wraps around the
    # ring, so it is the tune minus the accumulated advance rather than the
    # negative number the plain difference gives.
    delta_mu = mu[nxt] - mu
    delta_mu[-1] += tune
    phi = 2.0 * np.pi * delta_mu

    sin_phi = np.sin(phi)
    degenerate = np.abs(sin_phi) < MIN_SIN_PHASE_ADVANCE
    if degenerate.any():
        pairs = ", ".join(
            f"{names[i]}->{names[nxt[i]]} (sin={sin_phi[i]:+.4f})"
            for i in np.flatnonzero(degenerate)
        )
        raise ValueError(
            f"Cannot derive momentum dispersion in {plane}: the phase advance to the "
            f"next BPM is too close to a multiple of pi for {int(degenerate.sum())} "
            f"pair(s): {pairs}. D' inverts as 1/sin(dphi), so these carry no usable "
            "angle information."
        )

    m11 = np.sqrt(beta[nxt] / beta) * (np.cos(phi) + alfa * np.sin(phi))
    m12 = np.sqrt(beta[nxt] * beta) * sin_phi
    # The dispersion generated by bends between the two BPMs, taken from the
    # model. It is the only model-sourced term in the result.
    m13 = model_d[nxt] - m11 * model_d - m12 * model_dp

    momentum_dispersion = (measured_d[nxt] - m11 * measured_d - m13) / m12
    # The two measured dispersions enter linearly and come from independent
    # BPMs, so their errors add in quadrature. m11/m12 are model quantities and
    # are treated as exact here, consistent with how the model phase and beta
    # are treated everywhere else in the reconstruction.
    variance = (measured_d_err[nxt] ** 2 + (m11 * measured_d_err) ** 2) / m12**2
    return momentum_dispersion, np.sqrt(variance)


def derive_momentum_dispersion(
    measured: pd.DataFrame,
    model: pd.DataFrame,
    *,
    tunes: tuple[float, float],
) -> dict[str, np.ndarray]:
    """Derive ``dpx``/``dpy`` and their errors from measured ``dx``/``dy``.

    Args:
        measured: Ring-ordered frame carrying measured ``dx``/``dy``, and
            optionally ``dx_err``/``dy_err`` (assumed zero when absent).
        model: Frame on the same index carrying ``betx``/``alfx``/``mu1``/
            ``dx``/``dpx`` and their vertical counterparts. Phases are in turns.
        tunes: ``(q1, q2)``, used to close the ring for the final BPM pair.

    Returns:
        ``{"dpx": ..., "dpx_err": ..., "dpy": ..., "dpy_err": ...}``, each an
        array aligned with *measured*'s row order.

    Raises:
        KeyError: If a required column is missing from either frame.
        ValueError: If the frames are misaligned, hold fewer than two BPMs, or
            contain a BPM pair too close to a half-integer phase advance.
    """
    if not measured.index.equals(model.index):
        raise ValueError(
            "Measured and model frames must share one ring-ordered index to derive "
            "momentum dispersion"
        )
    if len(measured) < 2:
        raise ValueError(
            f"Deriving momentum dispersion needs at least two BPMs, got {len(measured)}"
        )
    # Each row pairs with the row after it and the last wraps to the first, so a
    # frame that is not in ring order silently pairs the wrong BPMs and produces
    # a plausible-looking wrong answer rather than an error.
    if "s" in model.columns:
        positions = model["s"].to_numpy(dtype=float)
        if not np.all(np.diff(positions) > 0):
            raise ValueError(
                "Momentum dispersion needs a ring-ordered frame, but the model 's' "
                "column is not strictly increasing"
            )

    names = measured.index.to_numpy()
    result: dict[str, np.ndarray] = {}
    for plane, (beta, alfa, mu, d, dp, tune_key) in _PLANE_COLUMNS.items():
        missing_model = [c for c in (beta, alfa, mu, d, dp) if c not in model.columns]
        if missing_model:
            raise KeyError(
                f"Model twiss is missing {missing_model}, required to derive "
                f"momentum dispersion in {plane}"
            )
        if d not in measured.columns:
            raise KeyError(f"Measured dispersion column {d!r} is required to derive {dp!r}")

        err_col = f"{d}_err"
        measured_err = (
            measured[err_col].to_numpy(dtype=float)
            if err_col in measured.columns
            else np.zeros(len(measured))
        )
        values, errors = _plane_momentum_dispersion(
            measured_d=measured[d].to_numpy(dtype=float),
            measured_d_err=measured_err,
            beta=model[beta].to_numpy(dtype=float),
            alfa=model[alfa].to_numpy(dtype=float),
            mu=model[mu].to_numpy(dtype=float),
            model_d=model[d].to_numpy(dtype=float),
            model_dp=model[dp].to_numpy(dtype=float),
            tune=float(tunes[0] if plane == "x" else tunes[1]),
            names=names,
            plane=plane,
        )
        result[dp] = values
        result[f"{dp}_err"] = errors
    return result
