name: Coverage

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: 'pyproject.toml'

      - name: Ensure pip, setuptools and wheel
        run: uv pip install --upgrade pip setuptools wheel

      # The uv pip should make & use an env from the Python install of the previous step
      - name: Install package
        run: uv pip install '.[test]'

      - name: Install dependencies from GitHub
        run: uv pip install git+https://github.com/jgray-19/xtrack_tools.git git+https://github.com/jgray-19/pymadng-utils.git

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
